// Prepares the embedding model for same-origin hosting under public/models/.
// Vercel's Hobby plan rejects static files over 100 MB and the int8 ONNX file is 118 MB, so the ONNX
// file is split into 10 MiB parts with a SHA-256 per part, and the small files are copied as they are.
// Usage: node scripts/split-model.mjs [sourceDir]
//   sourceDir defaults to the transformers.js cache: node_modules/@huggingface/transformers/.cache/<model>
//   (run `node eval/probe.mjs` once to download it). The source is Xenova/multilingual-e5-small (MIT).
import { createHash } from 'node:crypto';
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const MODEL_ID = 'Xenova/multilingual-e5-small';
const PART_BYTES = 10 * 1024 * 1024;
const root = fileURLToPath(new URL('../', import.meta.url));
const source =
  process.argv[2] ?? join(root, 'node_modules/@huggingface/transformers/.cache', MODEL_ID);
const outDir = join(root, 'public/models');
const modelDir = join(outDir, MODEL_ID);

// Sizes of the upstream files, from the Hugging Face listing; a mismatch means a partial download.
const EXPECTED = {
  'config.json': 658,
  'tokenizer.json': 17_082_730,
  'tokenizer_config.json': 443,
  'onnx/model_quantized.onnx': 118_308_185,
};
const sha256 = (buffer) => createHash('sha256').update(buffer).digest('hex');

try {
  for (const [file, size] of Object.entries(EXPECTED)) {
    const path = join(source, file);
    if (!existsSync(path))
      throw new Error(`Missing ${path}. Run node eval/probe.mjs to download the model.`);
    if (statSync(path).size !== size)
      throw new Error(
        `${file} is ${statSync(path).size} bytes, expected ${size}; the download is incomplete.`,
      );
  }
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(join(modelDir, 'onnx'), { recursive: true });

  const files = {};
  for (const file of ['config.json', 'tokenizer.json', 'tokenizer_config.json']) {
    copyFileSync(join(source, file), join(modelDir, file));
    files[file] = { size: EXPECTED[file], sha256: sha256(readFileSync(join(source, file))) };
  }

  const onnx = readFileSync(join(source, 'onnx/model_quantized.onnx'));
  const parts = [];
  for (let offset = 0, index = 0; offset < onnx.length; offset += PART_BYTES, index += 1) {
    const chunk = onnx.subarray(offset, Math.min(onnx.length, offset + PART_BYTES));
    const name = `onnx/model_quantized.onnx.part${String(index).padStart(3, '0')}`;
    writeFileSync(join(modelDir, name), chunk);
    parts.push({ name, size: chunk.length, sha256: sha256(chunk) });
  }
  files['onnx/model_quantized.onnx'] = { size: onnx.length, sha256: sha256(onnx), parts };

  const manifest = {
    version: 1,
    model: MODEL_ID,
    note: 'Generated by scripts/split-model.mjs. Upstream: https://huggingface.co/Xenova/multilingual-e5-small (MIT, from intfloat/multilingual-e5-small).',
    files,
  };
  // Read everything back: a copy on a failing disk or a syncing folder can differ from what was written.
  for (const [name, file] of Object.entries(files)) {
    for (const item of file.parts ?? [{ name, sha256: file.sha256 }]) {
      if (sha256(readFileSync(join(modelDir, item.name))) !== item.sha256)
        throw new Error(`${item.name} changed after it was written; run the script again.`);
    }
  }
  writeFileSync(join(outDir, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
  console.log(
    `Wrote ${parts.length} ONNX parts and ${Object.keys(files).length} files under ${outDir}`,
  );
  console.log(`ONNX sha256 ${files['onnx/model_quantized.onnx'].sha256}`);
} catch (error) {
  console.error(`Model split failed: ${error.message}`);
  process.exitCode = 1;
}
